
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 05 15:08:48 CST 2023
//----------------------------------------------------

package com.adolfosc.analizadores;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int DECIMAL = 12;
  public static final int MENOS = 8;
  public static final int CORIZQ = 5;
  public static final int UMENOS = 13;
  public static final int ENTERO = 11;
  public static final int POR = 9;
  public static final int CORDER = 6;
  public static final int PTCOMA = 2;
  public static final int DIVIDIDO = 10;
  public static final int EOF = 0;
  public static final int MAS = 7;
  public static final int PARIZQ = 3;
  public static final int error = 1;
  public static final int PARDER = 4;
  public static final int REVALUAR = 14;
}

